"""Initial migration

Revision ID: 75f03f2121f5
Revises: 
Create Date: 2024-11-17 14:54:19.624481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f03f2121f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_image', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('body_style', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('transmission', sa.String(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('top_speed', sa.Integer(), nullable=True),
    sa.Column('accident_history', sa.String(), nullable=True),
    sa.Column('current_condition', sa.String(), nullable=True),
    sa.Column('modifications', sa.String(), nullable=True),
    sa.Column('car_report', sa.String(), nullable=True),
    sa.Column('bids', sa.Integer(), nullable=True),
    sa.Column('starting_bid_price', sa.Integer(), nullable=True),
    sa.Column('current_bid_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cars'))
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], name=op.f('fk_bids_car_id_cars')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bids'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids')
    op.drop_table('cars')
    # ### end Alembic commands ###
