"""Initial migration

Revision ID: ce8cf79eb5a8
Revises: 
Create Date: 2024-10-02 14:49:01.755409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8cf79eb5a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('top_speed', sa.Integer(), nullable=True),
    sa.Column('accident_history', sa.String(), nullable=True),
    sa.Column('modifications', sa.String(), nullable=True),
    sa.Column('bids', sa.Integer(), nullable=True),
    sa.Column('starting_bid_price', sa.Integer(), nullable=True),
    sa.Column('current_bid_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cars'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
