"""Initial migration

Revision ID: f676c9ecefa8
Revises: 
Create Date: 2024-10-22 23:42:47.685149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f676c9ecefa8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('body_style', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('top_speed', sa.Integer(), nullable=True),
    sa.Column('accident_history', sa.String(), nullable=True),
    sa.Column('modifications', sa.String(), nullable=True),
    sa.Column('car_report', sa.String(), nullable=True),
    sa.Column('bids', sa.Integer(), nullable=True),
    sa.Column('starting_bid_price', sa.Integer(), nullable=True),
    sa.Column('current_bid_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cars'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
